"""empty message

Revision ID: 2fc46a9d4980
Revises: 740c42f36a7d
Create Date: 2020-03-05 17:27:32.616031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc46a9d4980'
down_revision = '740c42f36a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.alter_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'past_shows')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
